// frontend/src/components/weekly-board/PrintWeekView.tsx
// T-034: Print-optimized week view for schedules

interface PrintEvent {
  id: string;
  type: 'game' | 'practice';
  datetime: string;
  opponent?: string;
  teamName: string;
  facilityName?: string | null;
  status?: string;
}

interface PrintWeekViewProps {
  events: PrintEvent[];
  schoolName: string;
  teamName?: string;
  seasonName?: string;
  weekStart?: Date;
  weekEnd?: Date;
}

const formatDay = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  });
};

const formatTime = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
  });
};

const formatDateRange = (start?: Date, end?: Date): string => {
  if (!start || !end) return '';
  const opts: Intl.DateTimeFormatOptions = { month: 'long', day: 'numeric', year: 'numeric' };
  return `${start.toLocaleDateString('en-US', opts)} - ${end.toLocaleDateString('en-US', opts)}`;
};

export function PrintWeekView({
  events,
  schoolName,
  teamName,
  seasonName,
  weekStart,
  weekEnd,
}: PrintWeekViewProps) {
  // Sort events by datetime
  const sorted = [...events].sort(
    (a, b) => new Date(a.datetime).getTime() - new Date(b.datetime).getTime()
  );

  const now = new Date();

  return (
    <div className="print-week-view hidden print:block">
      {/* T-038: Print header */}
      <div className="text-center mb-6">
        <h1 className="text-xl font-bold">{schoolName}</h1>
        {teamName && <h2 className="text-lg">{teamName}</h2>}
        {seasonName && <p className="text-sm text-gray-600">{seasonName}</p>}
        {weekStart && weekEnd && (
          <p className="text-sm text-gray-500 mt-1">{formatDateRange(weekStart, weekEnd)}</p>
        )}
      </div>

      {/* T-034: Clean table layout */}
      <table className="w-full border-collapse border border-gray-400 text-sm">
        <thead>
          <tr className="bg-gray-100">
            <th className="border border-gray-400 px-3 py-2 text-left">Day</th>
            <th className="border border-gray-400 px-3 py-2 text-left">Time</th>
            <th className="border border-gray-400 px-3 py-2 text-left">Team</th>
            <th className="border border-gray-400 px-3 py-2 text-left">Opponent / Type</th>
            <th className="border border-gray-400 px-3 py-2 text-left">Facility</th>
            <th className="border border-gray-400 px-3 py-2 text-left">Status</th>
          </tr>
        </thead>
        <tbody>
          {sorted.length === 0 ? (
            <tr>
              <td colSpan={6} className="border border-gray-400 px-3 py-4 text-center text-gray-500">
                No events scheduled for this period.
              </td>
            </tr>
          ) : (
            sorted.map((event) => (
              <tr key={`${event.type}-${event.id}`}>
                <td className="border border-gray-400 px-3 py-2">{formatDay(event.datetime)}</td>
                <td className="border border-gray-400 px-3 py-2">{formatTime(event.datetime)}</td>
                <td className="border border-gray-400 px-3 py-2">{event.teamName}</td>
                <td className="border border-gray-400 px-3 py-2">
                  {event.type === 'game' && event.opponent
                    ? `vs ${event.opponent}`
                    : event.type === 'practice'
                      ? 'Practice'
                      : '-'}
                </td>
                <td className="border border-gray-400 px-3 py-2">{event.facilityName ?? '-'}</td>
                <td className="border border-gray-400 px-3 py-2">{event.status ?? 'Scheduled'}</td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      {/* T-038: Print footer */}
      <div className="mt-6 pt-4 border-t border-gray-300 flex justify-between text-xs text-gray-500">
        <span>Generated by AthleticOS</span>
        <span>Printed {now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })}</span>
      </div>
    </div>
  );
}
